name: Simple Actions

on:
  push:
    branches: [ main ]

jobs: 
  build:
    # A runner is any machine with GHA installed
    # This is a GitHub hosted runner
    runs-on: ubuntu-latest

    steps: 
    # This is a standard action. The checkout action is a standard 
    # action that you must include before othe actions where your workflow 
    # requires a copy of your code
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: Betray a secreyt
      run: echo The secret is ${{MY_FIRST_SECRET}}

    - name: Run a multi-line script
      run: | 
        echo Add other actions to build,
        echo test and deploy your script
