name: Simple Actions

on:
  push:
    branches: [ main ]

jobs: 
  build:
    # A runner is any machine with GHA installed
    # This is a GitHub hosted runner
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps: 
    # This is a standard action. The checkout action is a standard 
    # action that you must include before othe actions where your workflow 
    # requires a copy of your code
    - uses: actions/checkout@v2

    - name: Have we got node?
      run: node -v
      
    - name: Have we got NPM?
      run: npm -v

    - name: Install Angular
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: cd demo-application && npm install

    - name: Build the app
      run: pwd && ng build
    
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: gha-demo-bucket
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-2
        SOURCE_DIR: "demo-application/dist/demo-application"
      
    - name: Betray a secret
      run: echo The secret is ${{secrets.MY_FIRST_SECRET}}

    - name: Run a multi-line script
      run: | 
        echo Add other actions to build,
        echo test and deploy your script
